name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
          service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.14'

      - name: Test Application
        run: uv run pytest

      - name: Setup Node.js (version 20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Test Frontend
        working-directory: ./frontend
        run: npm run test:unit

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker Auth for Artifact Registry
        run: |-
          echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ vars.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_PATH="${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/runrun-rest:${{ github.sha }}"
          docker build -t $IMAGE_PATH .
          docker push $IMAGE_PATH
          echo "IMAGE=$IMAGE_PATH" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: run-run-rest
          region: ${{ vars.GCP_REGION }}
          image: ${{ env.IMAGE }}
          flags: '--allow-unauthenticated'
          env_vars: |-
            ZITADEL_DISCOVERY_URL=${{ secrets.ZITADEL_DISCOVERY_URL }}
            ZITADEL_CLIENT_ID=${{ secrets.ZITADEL_CLIENT_ID }}
            ZITADEL_CLIENT_SECRET=${{ secrets.ZITADEL_CLIENT_SECRET }}
            SESSION_SECRET_KEY=${{ secrets.SESSION_SECRET_KEY }}
            STRAVA_API_TOKEN=${{ secrets.STRAVA_API_TOKEN }}
            STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }}
            STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}
            ENVIRONMENT=production

