name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
          service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.14'

      - name: Test Application
        run: uv run pytest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker Auth for Artifact Registry
        run: |-
          echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ vars.GAR_LOCATION }}-docker.pkg.dev

      - name: Build OCI Image with pycontainer-build
        run: |
          IMAGE_PATH="${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/runrun-rest:${{ github.sha }}"
          uv run pycontainer build --tag $IMAGE_PATH --context . --include-deps
          docker push $IMAGE_PATH
          echo "IMAGE=$IMAGE_PATH" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: run-run-rest
          region: ${{ vars.GCP_REGION }}
          image: ${{ env.IMAGE }}
          flags: '--allow-unauthenticated'
